=== CrawfordWCR/clickframes/tags/clickframes-0.9.9/maven-plugin/src/test/resources/clickframes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns="http://www.clickframes.org"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:isg="http://www.clickframes.org"
  targetNamespace="http://www.clickframes.org"
  elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xsd:element name="project" type="isg:projectType">
    <xsd:unique name="uniquePageIdConstraint">
      <xsd:selector xpath="isg:page" />
      <xsd:field xpath="@id" />
    </xsd:unique>

    <xsd:unique name="uniqueLinkSetIdConstraint">
      <xsd:selector xpath="isg:linkSet" />
      <xsd:field xpath="@id" />
    </xsd:unique>

    <xsd:key name="pageIndex">
      <xsd:selector xpath="isg:page" />
      <xsd:field xpath="@id" />
    </xsd:key>

    <xsd:key name="linkSetIndex">
      <xsd:selector xpath="isg:linkSet" />
      <xsd:field xpath="@id" />
    </xsd:key>

    <xsd:keyref name="outcomePageRefForeignKeyConstraint"
      refer="isg:pageIndex">
      <xsd:selector xpath=".//isg:outcome/isg:pageRef" />
      <xsd:field xpath="." />
    </xsd:keyref>

    <xsd:keyref name="externalLinkPageRefForeignKeyConstraint"
      refer="isg:pageIndex">
      <xsd:selector xpath=".//isg:link/isg:pageRef" />
      <xsd:field xpath="." />
    </xsd:keyref>

    <xsd:keyref name="pageLinkSetRefForeignKeyConstraint"
      refer="isg:linkSetIndex">
      <xsd:selector xpath="isg:page/isg:linkSetRef" />
      <xsd:field xpath="@id" />
    </xsd:keyref>
  </xsd:element>

  <xsd:complexType name="linkSetType">
    <xsd:sequence>
      <xsd:element name="title" type="isg:nonEmptyString" />
      <xsd:element name="fact" minOccurs="0" maxOccurs="unbounded"
        type="isg:nonEmptyString" />
      <xsd:element name="link" maxOccurs="unbounded"
        type="isg:linkType" />
    </xsd:sequence>
    <xsd:attribute name="id" use="required" type="xsd:string" />
    <xsd:attribute name="global" use="optional" type="xsd:boolean" />
  </xsd:complexType>

  <xsd:complexType name="projectType">
    <xsd:sequence>
      <xsd:element name="title" type="isg:nonEmptyString" maxOccurs="1" />
      <xsd:element name="outcome" type="isg:outcomeType" minOccurs="0"
        maxOccurs="unbounded" />
      <xsd:element name="linkSet" type="isg:linkSetType" minOccurs="0"
        maxOccurs="unbounded" />
      <xsd:element name="page" type="isg:pageType" minOccurs="1"
        maxOccurs="unbounded" />
    </xsd:sequence>
  </xsd:complexType>

  <xsd:simpleType name="descriptionType">
    <xsd:restriction base="xsd:string"></xsd:restriction>
  </xsd:simpleType>

  <xsd:complexType name="pageType">
    <xsd:sequence minOccurs="1">
      <xsd:element name="title" maxOccurs="1" type="isg:nonEmptyString" />
      <xsd:element name="description" maxOccurs="1"
        type="isg:descriptionType" />
      <xsd:element name="fact" minOccurs="0" maxOccurs="unbounded"
        type="isg:nonEmptyString" />
      <xsd:element name="input" minOccurs="0" maxOccurs="unbounded"
        type="isg:inputType" />
      <xsd:element name="action" minOccurs="0" maxOccurs="unbounded"
        type="isg:actionType" />
      <xsd:element name="link" minOccurs="0" maxOccurs="unbounded"
        type="isg:linkType" />
      <xsd:element name="linkSetRef" minOccurs="0" maxOccurs="unbounded"
        type="isg:linkSetRefType" />
      <xsd:element name="property" minOccurs="0" maxOccurs="unbounded"
        type="isg:propertyType" />
    </xsd:sequence>
    <xsd:attribute name="id" use="required" type="xsd:string" />
  </xsd:complexType>

  <xsd:complexType name="inputType">
    <xsd:sequence>
      <xsd:element name="title" type="isg:nonEmptyString" />
      <xsd:element name="description" type="xsd:string" />
      <xsd:element name="validation" type="isg:validationType"
        minOccurs="0" maxOccurs="unbounded" />
    </xsd:sequence>
    <xsd:attribute name="type" use="required" type="xsd:string" />
  </xsd:complexType>

  <xsd:complexType name="actionType">
    <xsd:sequence>
      <xsd:element name="title" type="isg:nonEmptyString" />
      <xsd:element name="outcome" maxOccurs="unbounded"
        type="isg:outcomeType" />
    </xsd:sequence>
  </xsd:complexType>

  <xsd:complexType name="outcomeType">
    <xsd:sequence>
      <xsd:element name="title" type="isg:nonEmptyString" />
      <xsd:element name="description" minOccurs="0" maxOccurs="1"
        type="xsd:string" />
      <xsd:choice>
        <xsd:element name="href" type="isg:nonEmptyString" />
        <xsd:element name="pageRef" type="isg:nonEmptyString" />
      </xsd:choice>
      <xsd:element name="fact" minOccurs="0" maxOccurs="unbounded"
        type="isg:nonEmptyString" />
    </xsd:sequence>
    <xsd:attribute name="negative" use="optional" type="xsd:boolean" />
  </xsd:complexType>

  <xsd:complexType name="linkSetRefType">
    <xsd:attribute name="id" use="required" type="xsd:string" />
  </xsd:complexType>

  <xsd:complexType name="propertyType">
    <xsd:attribute name="name" use="required" type="xsd:string" />
    <xsd:attribute name="value" use="required" type="xsd:string" />
  </xsd:complexType>

  <xsd:complexType name="validationType">
    <xsd:attribute name="type" use="required" type="xsd:string" />
    <xsd:attribute name="description" use="optional" type="xsd:string" />
  </xsd:complexType>

  <xsd:complexType name="linkType">
    <xsd:sequence>
      <xsd:element name="title" type="isg:nonEmptyString" />
      <xsd:element name="description" minOccurs="0" maxOccurs="1"
        type="xsd:string" />
      <xsd:choice>
        <xsd:element name="href" type="isg:nonEmptyString" />
        <xsd:element name="pageRef" type="isg:nonEmptyString" />
      </xsd:choice>
      <xsd:element name="fact" minOccurs="0" maxOccurs="unbounded"
        type="isg:nonEmptyString" />
    </xsd:sequence>
  </xsd:complexType>

  <xsd:simpleType name='nonEmptyString'>
    <xsd:restriction base='xsd:string'>
      <xsd:minLength value='1' />
    </xsd:restriction>
  </xsd:simpleType>
</xsd:schema>

=== CrawfordWCR/clickframes/tags/clickframes-0.9.9-old/maven-plugin/src/test/resources/clickframes_junit.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<project xmlns="http://www.clickframes.org"
  xmlns:isg="http://www.clickframes.org"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.clickframes.org clickframes.xsd">
  <title>Sample Project Title</title>

  <outcome negative="true">
    <title>Global Outcome 1</title>
    <description>This outcome is shared in all states</description>
    <pageRef>page1</pageRef>
  </outcome>

  <linkSet id="linkSet1">
    <title>Link Set 1</title>
    <fact>fact1</fact>
    <link>
      <title>External Link 1 Title</title>
      <description>External Link 1 Description</description>
      <href>mailto:externalLink1</href>
    </link>
    <link>
      <title>Internal Link 1 Title</title>
      <pageRef>page2</pageRef>
    </link>
  </linkSet>

  <linkSet id="linkSet2" global="true">
    <title>Link Set 2</title>
    <link>
      <title>External Link 2.1 Title</title>
      <href>mailto:externalLink2.1</href>
    </link>
    <link>
      <title>External Link 2.2 Title</title>
      <href>http://externalLink2.2</href>
    </link>
  </linkSet>

  <page id="page1">
    <title>Page 1 Title</title>

    <description>Page 1 Description</description>

    <fact>Fact 1</fact>
    <fact>Fact 2</fact>

    <input type="text">
      <title>TextInput 1 title</title>
      <description>Enter text input 1</description>
      <validation type="required" />
      <validation type="length(min=8)" />
      <validation type="regex(/^\S+$/)"
        description="INPUT may not contain whitespace" />
    </input>

    <input type="checkbox">
      <title>CheckboxInput 1 title</title>
      <description>Enter checkbox input 1</description>
    </input>

    <action>
      <title>Action 1 title</title>

      <outcome>
        <title>Outcome to page1</title>
        <description>This will take your to page1</description>
        <pageRef>page1</pageRef>
        <fact>Fact 1</fact>
        <fact>Fact 2</fact>
      </outcome>

      <outcome>
        <title>Outcome to page2</title>
        <href>externalLink</href>
      </outcome>
    </action>

    <action>
      <title>Action 2 title</title>

      <outcome>
        <title>Outcome to page1</title>
        <pageRef>page1</pageRef>
      </outcome>

      <outcome>
        <title>Outcome to page2</title>
        <pageRef>page3</pageRef>
      </outcome>
    </action>

    <link>
      <title>Link to Page 2</title>
      <pageRef>page2</pageRef>
      <fact>Fact 1</fact>
    </link>

    <link>
      <title>Link to Page 3</title>
      <pageRef>page3</pageRef>
    </link>

    <linkSetRef id="linkSet1" />
    <linkSetRef id="linkSet2" />

    <property name="property1" value="value1" />
  </page>

  <page id="page2">
    <title>Page2</title>
    <description>
      This is Page 2 of the sample application. You can put a very long
      description here.
    </description>
    <action>
      <title>Action 2a title</title>
      <outcome>
        <title>Page 3</title>
        <pageRef>page3</pageRef>
      </outcome>
    </action>
  </page>

  <page id="page3">
    <title>Page3</title>
    <description>
      This is Page 3 of the sample application. You can put a very long
      description here.
    </description>
  </page>
</project>
